[[tests]]
test_name = "racfed_eddi_ml_add"
source_file = "c/multi_instruction/add.c"
expected_output = "30"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_ml_function_call"
source_file = "c/multi_instruction/function.c"
expected_output = "foo() 25"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_preserve_runtime_sig"
source_file = "c/multi_instruction/call_less_two.c"
expected_output = "0"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_ml_if_then_else"
source_file = "c/multi_instruction/if_then_else.c"
expected_output = "1001"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_ml_phi_instruction"
source_file = "c/multi_instruction/phi.c"
expected_output = "SUCCESS"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_function_pointer"
source_file = "c/control_flow/function_pointer.c"
expected_output = "42"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_loop_exit"
source_file = "c/control_flow/loop_exit.c"
expected_output = "2"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_n-branch_eddi"
source_file = "c/control_flow/nested-branch.c"
expected_output = "6"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_s-branch_eddi"
source_file = "c/control_flow/simple-branch.c"
expected_output = "OK"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_s-case_eddi"
source_file = "c/control_flow/switch-case.c"
expected_output = "300"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_data_dep_branches"
source_file = "c/data_duplication_integrity/data_dep_branches.c"
expected_output = "7"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_global_var_across_functions"
source_file = "c/data_duplication_integrity/global_var_across_functions.c"
expected_output = "2"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_misc_data_dup"
source_file = "c/data_duplication_integrity/misc_data_dup.c"
expected_output = "OK"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_volatile_io"
source_file = "c/data_duplication_integrity/volatile_io.c"
expected_output = "42"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_arit_pipeline"
source_file = "c/misc_math/arit_pipeline.c"
expected_output = "3"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_mixed_ops"
source_file = "c/misc_math/mixed_ops.c"
expected_output = "14.5"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_xor_cypher"
source_file = "c/misc_math/xor_cypher.c"
expected_output = "SUCCESS"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_ml_multi_if_else"
source_file = "c/multi_instruction/multi_if_then_else.c"
expected_output = "r > 200"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_crc32_mibench"
source_file = "c/mibench/crc32_mibench.c"
expected_output = "SUCCESS"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_dijkstra"
source_file = "c/mibench/dijkstra_small_mibench.c"
expected_output = "SUCCESS"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_basicmath"
source_file = "c/mibench/basicmath.c"
expected_output = "SUCCESS"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_insertsort"
source_file = "c/malardalen/insertsort.c"
expected_output = "Sorted array: 0 2 3 4 5 6 7 8 9 10 11 \n"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_bsort100"
source_file = "c/malardalen/bsort100.c"
expected_output = "Sorted array: -100 -99 -98 -97 -96 -95 -94 -93 -92 -91 -90 -89 -88 -87 -86 -85 -84 -83 -82 -81 -80 -79 -78 -77 -76 -75 -74 -73 -72 -71 -70 -69 -68 -67 -66 -65 -64 -63 -62 -61 -60 -59 -58 -57 -56 -55 -54 -53 -52 -51 -50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 \n"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_matmult"
source_file = "c/malardalen/matmult.c"
expected_output = "SUCCESS\n"
aspis_options = "--eddi --racfed"

[[tests]]
test_name = "racfed_eddi_multiple_functions"
source_file = "c/ourbench/multiple_functions.c"
expected_output = "z[0] = 4\nz[1] = 9\nz[2] = 4\nz[3] = 9\nz[4] = 4\nz[5] = 9\nz[6] = 4\nz[7] = 9\nz[8] = 4\nz[9] = 9\n"
aspis_options = "--eddi --racfed"

